export { default as KIA } from "./components/KIA"
export { default as DOOSAN } from "./components/DOOSAN"
export { default as LG } from "./components/LG"
export { default as SSG } from "./components/SSG"
export { default as KIWOOM } from "./components/KIWOOM"
export { default as KT } from "./components/KT"
export { default as NC } from "./components/NC"
export { default as SAMSUNG } from "./components/SAMSUNG"
export { default as LOTTE } from "./components/LOTTE"
export { default as HANWHA } from "./components/HANWHA"

export type { LogoProps } from "./components/types"
